[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/_next/static/chunks/*.js"
  [headers.values]
    Content-Type = "application/javascript"
  
[[headers]]
  for = "/_next/static/css/*.css"
  [headers.values]
    Content-Type = "text/css"
  
[[headers]]
  for = "/api/*"
  [headers.values]
    Content-Type = "application/json"