import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ReCaptchaProvider } from "next-recaptcha-v3";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="layout-flex">
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/form">Form</Link>
            <Link href="/form2">Form2</Link>
          </div>
        </div>
        <ReCaptchaProvider reCaptchaKey={process.env.RECAPTCHA_SITE_KEY || " "}>
        {children}
        </ReCaptchaProvider>
      </body>
    </html>
  );
}
